### ISSUE TITLE
Python 2 & 3 conflict

### ISSUE THREAD

**Issue by bsaldivaremc2** [overlap-ai/words2map#5]
Best regards.
My system runs in python3.5 normally. I see that words2map runs on python2 (seeing the print statements of the code). While running the ./install.sh I can see that the dependencies are being installed with py35 in the words2map/bin/ environment. How to set up the virtual environment create by words2map with python2?

**Comment by legel** [comment]
Hello, you can replace this line in install.sh:
`conda create --name words2map --yes cython scikit-learn gensim seaborn`
with
`conda create --name words2map --yes python=2.7 cython scikit-learn gensim seaborn`
...and this should help.

**Comment by bsaldivaremc2** [comment]
Great! After the change it installed normally. 
Nonetheless, while executing 
`python words2map.py`
y get:
`Segmentation fault (core dumped)`

**Comment by legel** [comment]
Interesting. How much RAM do you have available? Minimum is at least 500 MB to load the word vectors. Assuming this popped up during the loading process? I've seen this when I tried to run on a EC2 nano instance, e.g., and solution was to go bigger with the RAM if you're working in the cloud...

**Comment by bsaldivaremc2** [comment]
I was using a laptop, 4 GiB RAM with ubuntu, with 1.5 GiB free. Error present.
Then I tried with an Ubuntu with 8GiB RAM, command line only, before starting the program 1GiB used. The program started, reaching in average 4 GiB.
